# eDP-1 (laptop) → 1, 2, 3
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1

# DP-3 → 4, 5, 6
workspace = 4, monitor:DP-3, default:true
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-3

# HDMI-A-1 → 7, 8, 9
workspace = 7, monitor:HDMI-A-1, default:true
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
